<option value="+49">Germany (+49)</option>
<option value="+353">Ireland (+353)</option>
<option value="+31">Netherlands (+31)</option>
<option value="+34">Spain (+34)</option>
<option value="+46">Sweden (+46)</option>
<option value="+44">United Kingdom (+44)</option>
<option value="+1">United States of America (+1)</option>
<option value="+93">Afghanistan (+93)</option>
<option value="+355">Albania (+355)</option>
<option value="+213">Algeria (+213)</option>
<option value="+684">American Samoa (+684)</option>
<option value="+376">Andorra (+376)</option>
<option value="+244">Angola (+244)</option>
<option value="+264">Anguilla (+264)</option>
<option value="+672">Antarctica (+672)</option>
<option value="+268">Antigua and Barbuda (+268)</option>
<option value="+54">Argentina (+54)</option>
<option value="+374">Armenia (+374)</option>
<option value="+297">Aruba (+297)</option>
<option value="+61">Australia (+61)</option>
<option value="+43">Austria (+43)</option>
<option value="+994">Azerbaijan (+994)</option>
<option value="+242">Bahamas (+242)</option>
<option value="+973">Bahrain (+973)</option>
<option value="+880">Bangladesh (+880)</option>
<option value="+246">Barbados (+246)</option>
<option value="+375">Belarus (+375)</option>
<option value="+32">Belgium (+32)</option>
<option value="+501">Belize (+501)</option>
<option value="+229">Benin (+229)</option>
<option value="+441">Bermuda (+441)</option>
<option value="+975">Bhutan (+975)</option>
<option value="+591">Bolivia (+591)</option>
<option value="+387">Bosnia and Herzegovina (+387)</option>
<option value="+267">Botswana (+267)</option>
<option value="+55">Brazil (+55)</option>
<option value="+246">British Indian Ocean Territory (+246)</option>
<option value="+673">Brunei Darussalam (+673)</option>
<option value="+359">Bulgaria (+359)</option>
<option value="+226">Burkina Faso (+226)</option>
<option value="+257">Burundi (+257)</option>
<option value="+855">Cambodia (+855)</option>
<option value="+237">Cameroon (+237)</option>
<option value="+1">Canada (+1)</option>
<option value="+238">Cape Verde (+238)</option>
<option value="+345">Cayman Islands (+345)</option>
<option value="+236">Central African Republic (+236)</option>
<option value="+235">Chad (+235)</option>
<option value="+56">Chile (+56)</option>
<option value="+86">China (+86)</option>
<option value="+53">Christmas Island (+53)</option>
<option value="+61">Cocos (Keeling) Islands (+61)</option>
<option value="+57">Colombia (+57)</option>
<option value="+269">Comoros (+269)</option>
<option value="+243">Congo, Democratic Republic of (+243)</option>
<option value="+242">Congo (+242)</option>
<option value="+682">Cook Islands (+682)</option>
<option value="+506">Costa Rica (+506)</option>
<option value="+385">Croatia (+385)</option>
<option value="+53">Cuba (+53)</option>
<option value="+599">Curaçao (+599)</option>
<option value="+357">Cyprus (+357)</option>
<option value="+420">Czech Rep. (+420)</option>
<option value="+225">Côte d’Ivoire (+225)</option>
<option value="+45">Denmark (+45)</option>
<option value="+253">Djibouti (+253)</option>
<option value="+767">Dominica (+767)</option>
<option value="+1">Dominican Republic (+1)</option>
<option value="+593">Ecuador (+593)</option>
<option value="+20">Egypt (+20)</option>
<option value="+503">El Salvador (+503)</option>
<option value="+240">Equatorial Guinea (+240)</option>
<option value="+291">Eritrea (+291)</option>
<option value="+372">Estonia (+372)</option>
<option value="+251">Ethiopia (+251)</option>
<option value="+500">Falkland Islands (Malvinas) (+500)</option>
<option value="+298">Faroe Islands (+298)</option>
<option value="+679">Fiji (+679)</option>
<option value="+358">Finland (+358)</option>
<option value="+33">France (+33)</option>
<option value="+594">French Guiana (+594)</option>
<option value="+689">French Polynesia (+689)</option>
<option value="+241">Gabon (+241)</option>
<option value="+220">Gambia (+220)</option>
<option value="+995">Georgia (+995)</option>
<option value="+49">Germany (+49)</option>
<option value="gh">Ghana (+233)</option>
<option value="gi">Gibraltar (+350)</option>
<option value="gr">Greece (+30)</option>
<option value="gl">Greenland (+299)</option>
<option value="gd">Grenada (+1473)</option>
<option value="gp">Guadeloupe (+590)</option>
<option value="gu">Guam (+671)</option>
<option value="gt">Guatemala (+502)</option>
<option value="gw">Guinea-Bissau (+245)</option>
<option value="gn">Guinea (+224)</option>
<option value="gy">Guyana (+592)</option>
<option value="ht">Haiti (+509)</option>
<option value="va">Holy See (Vatican City State) (+39)</option>
<option value="hn">Honduras (+504)</option>
<option value="hk">Hong Kong (+852)</option>
<option value="hu">Hungary (+36)</option>
<option value="is">Iceland (+354)</option>
<option value="in">India (+91)</option>
<option value="id">Indonesia (+62)</option>
<option value="ir">Iran (+98)</option>
<option value="iq">Iraq (+964)</option>
<option value="ie">Ireland (+353)</option>
<option value="im">Isle of Man (+44)</option>
<option value="il">Israel (+972)</option>
<option value="it">Italy (+39)</option>
<option value="jm">Jamaica (+876)</option>
<option value="jp">Japan (+81)</option>
<option value="jo">Jordan (+962)</option>
<option value="kz">Kazakhstan (+7)</option>
<option value="ke">Kenya (+254)</option>
<option value="ki">Kiribati (+686)</option>
<option value="kr">Korea, Rep. of (+82)</option>
<option value="xk">Kosovo, Republic of (+383)</option>
<option value="kw">Kuwait (+965)</option>
<option value="kg">Kyrgyzstan (+996)</option>
<option value="la">Laos (+856)</option>
<option value="lv">Latvia (+371)</option>
<option value="lb">Lebanon (+961)</option>
<option value="ls">Lesotho (+266)</option>
<option value="lr">Liberia (+231)</option>
<option value="ly">Libya (+218)</option>
<option value="li">Liechtenstein (+423)</option>
<option value="lt">Lithuania (+370)</option>
<option value="lu">Luxembourg (+352)</option>
<option value="mo">Macao (+853)</option>
<option value="mk">Macedonia, Rep. of (+389)</option>
<option value="mg">Madagascar (+261)</option>
<option value="mw">Malawi (+265)</option>
<option value="my">Malaysia (+60)</option>
<option value="mv">Maldives (+960)</option>
<option value="ml">Mali (+223)</option>
<option value="mt">Malta (+356)</option>
<option value="mh">Marshall Islands (+692)</option>
<option value="mq">Martinique (+596)</option>
<option value="mr">Mauritania (+222)</option>
<option value="mu">Mauritius (+230)</option>
<option value="yt">Mayotte (+269)</option>
<option value="mx">Mexico (+52)</option>
<option value="fm">Micronesia, Federated States of (+691)</option>
<option value="md">Moldova, Republic of (+373)</option>
<option value="mc">Monaco (+377)</option>
<option value="mn">Mongolia (+976)</option>
<option value="me">Montenegro (+382)</option>
<option value="ms">Montserrat (+664)</option>
<option value="ma">Morocco (+212)</option>
<option value="mz">Mozambique (+258)</option>
<option value="mm">Myanmar (+95)</option>
<option value="na">Namibia (+264)</option>
<option value="nr">Nauru (+674)</option>
<option value="np">Nepal (+977)</option>
<option value="nl">Netherlands (+31)</option>
<option value="nc">New Caledonia (+687)</option>
<option value="nz">New Zealand (+64)</option>
<option value="ni">Nicaragua (+505)</option>
<option value="ne">Niger (+227)</option>
<option value="ng">Nigeria (+234)</option>
<option value="nu">Niue (+683)</option>
<option value="nf">Norfolk Island (+672)</option>
<option value="mp">Northern Mariana Islands (+670)</option>
<option value="no">Norway (+47)</option>
<option value="om">Oman (+968)</option>
<option value="pk">Pakistan (+92)</option>
<option value="pw">Palau (+680)</option>
<option value="ps">Palestinian Territory, Occupied (+970)</option>
<option value="pa">Panama (+507)</option>
<option value="pg">Papua New Guinea (+675)</option>
<option value="py">Paraguay (+595)</option>
<option value="pe">Peru (+51)</option>
<option value="ph">Philippines, Rep. of the (+63)</option>
<option value="pn">Pitcairn Islands (+872)</option>
<option value="pl">Poland (+48)</option>
<option value="pt">Portugal (+351)</option>
<option value="pr">Puerto Rico (+1787)</option>
<option value="qa">Qatar (+974)</option>
<option value="re">Reunion (+262)</option>
<option value="ro">Romania (+40)</option>
<option value="ru">Russia (+7)</option>
<option value="rw">Rwanda (+250)</option>
<option value="sh">Saint Helena (+290)</option>
<option value="kn">Saint Kitts and Nevis (+869)</option>
<option value="lc">Saint Lucia (+758)</option>
<option value="mf">Saint Martin (French part) (+590)</option>
<option value="pm">Saint Pierre and Miquelon (+508)</option>
<option value="vc">Saint Vincent and the Grenadines (+784)</option>
<option value="ws">Samoa (+685)</option>
<option value="sm">San Marino (+378)</option>
<option value="st">Sao Tome and Principe (+239)</option>
<option value="sa">Saudi Arabia (+966)</option>
<option value="sn">Senegal (+221)</option>
<option value="rs">Serbia (+381)</option>
<option value="sc">Seychelles (+248)</option>
<option value="sl">Sierra Leone (+232)</option>
<option value="sg">Singapore (+65)</option>
<option value="sx">Sint Maarten (Dutch part) (+599)</option>
<option value="sk">Slovakia (+421)</option>
<option value="si">Slovenia (+386)</option>
<option value="sb">Solomon Islands (+677)</option>
<option value="so">Somalia (+252)</option>
<option value="za">South Africa (+27)</option>
<option value="gs">South Georgia and the South Sandwich Islands (+998)</option>
<option value="es">Spain (+34)</option>
<option value="lk">Sri Lanka (+94)</option>
<option value="sd">Sudan (+249)</option>
<option value="sr">Suriname (+597)</option>
<option value="sj">Svalbard and Jan Mayen (+79)</option>
<option value="sz">Swaziland (+268)</option>
<option value="se">Sweden (+46)</option>
<option value="ch">Switzerland (+41)</option>
<option value="sy">Syrian Arab Republic (+963)</option>
<option value="tw">Taiwan, Province of China (+886)</option>
<option value="tj">Tajikistan (+992)</option>
<option value="tz">Tanzania, United Republic of (+255)</option>
<option value="tf">Territory of the French Southern and Antarctic Lands ()</option>
<option value="th">Thailand (+66)</option>
<option value="tl">Timor-Leste (+670)</option>
<option value="tg">Togo (+228)</option>
<option value="tk">Tokelau (+690)</option>
<option value="to">Tonga (+676)</option>
<option value="tt">Trinidad and Tobago (+868)</option>
<option value="tn">Tunisia (+216)</option>
<option value="tr">Turkey (+90)</option>
<option value="tm">Turkmenistan (+993)</option>
<option value="tc">Turks and Caicos Islands (+649)</option>
<option value="tv">Tuvalu (+688)</option>
<option value="ug">Uganda (+256)</option>
<option value="ua">Ukraine (+380)</option>
<option value="ae">United Arab Emirates (+971)</option>
<option value="gb">United Kingdom (+44)</option>
<option value="um">United States Minor Outlying Islands (+808)</option>
<option value="us">United States of America (+1)</option>
<option value="uy">Uruguay (+598)</option>
<option value="uz">Uzbekistan (+998)</option>
<option value="vu">Vanuatu (+678)</option>
<option value="ve">Venezuela, Bolivarian Republic of (+58)</option>
<option value="vn">Vietnam (+84)</option>
<option value="vg">Virgin Islands, British (+284)</option>
<option value="vi">Virgin Islands, U.S. (+340)</option>
<option value="wf">Wallis and Futuna (+681)</option>
<option value="eh">Western Sahara (+212)</option>
<option value="ye">Yemen (+967)</option>
<option value="zm">Zambia (+260)</option>
<option value="zw">Zimbabwe (+263)</option>